/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exemplorelatorioswing;

import exemplorelatorioswing.utils.ReportUtils;
import java.awt.EventQueue;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.sql.DataSource;
import net.sf.jasperreports.engine.JRException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.ConfigurableApplicationContext;

/**
 *
 * @author Prof. Dr. David Buzatto
 */
@SpringBootApplication
public class JanelaPrincipal extends javax.swing.JFrame {

    @Autowired
    private DataSource dataSource;
    
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRelatorioClientes = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnNome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exemplo de Aplicação Spring com Relatório em Swing");

        btnRelatorioClientes.setText("Gerar Relatório de Clientes");
        btnRelatorioClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioClientesActionPerformed(evt);
            }
        });

        lblNome.setText("Nome:");

        btnNome.setText("Gerar Relatório de Clientes por Nome");
        btnNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRelatorioClientes)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRelatorioClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNome))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelatorioClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioClientesActionPerformed
        
        try {
            ReportUtils.openReport( "Relatório de Clientes", 
                    getClass().getClassLoader().getResourceAsStream( 
                            "relatorios/Clientes.jasper" ), 
                    null, dataSource.getConnection() );
        } catch ( JRException | SQLException exc ) {
            exc.printStackTrace();
        }
        
    }//GEN-LAST:event_btnRelatorioClientesActionPerformed

    private void btnNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNomeActionPerformed
        
        try {
            
            Map<String, String> parametros = new HashMap<>();
            parametros.put( "nome", txtNome.getText() );
            
            ReportUtils.openReport( "Relatório de Clientes por Nome", 
                    getClass().getClassLoader().getResourceAsStream( 
                            "relatorios/ClientesPorNome.jasper" ), 
                    parametros, dataSource.getConnection() );
            
        } catch ( JRException | SQLException exc ) {
            exc.printStackTrace();
        }
        
    }//GEN-LAST:event_btnNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {

        ConfigurableApplicationContext ctx = new SpringApplicationBuilder( JanelaPrincipal.class )
                .headless( false ).run( args );

       EventQueue.invokeLater( new Runnable() {
            public void run() {
                JanelaPrincipal app = ctx.getBean( JanelaPrincipal.class );
                app.setVisible( true );
            }
        } );
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNome;
    private javax.swing.JButton btnRelatorioClientes;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
