-- as importações durante o desenvolvimento serão feitas com codificação
-- errada. em produção os dados serão armazenados corretamente.

delete from item_venda;
delete from venda;
delete from produto;
delete from cliente;
delete from cidade;
delete from estado;

INSERT INTO estado(id, nome, sigla) VALUES(1, 'São Paulo', 'SP');
INSERT INTO estado(id, nome, sigla) VALUES(2, 'Minas Gerais', 'MG');
INSERT INTO estado(id, nome, sigla) VALUES(3, 'Paraná', 'PR');

INSERT INTO estado(nome, sigla) VALUES('Exemplo 00', '00');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 01', '01');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 02', '02');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 03', '03');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 04', '04');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 05', '05');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 06', '06');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 07', '07');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 08', '08');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 09', '09');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 10', '10');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 11', '11');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 12', '12');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 13', '13');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 14', '14');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 15', '15');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 16', '16');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 17', '17');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 18', '18');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 19', '19');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 20', '20');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 21', '21');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 22', '22');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 23', '23');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 24', '24');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 25', '25');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 26', '26');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 27', '27');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 28', '28');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 29', '29');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 30', '30');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 31', '31');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 32', '32');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 33', '33');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 34', '34');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 35', '35');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 36', '36');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 37', '37');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 38', '38');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 39', '39');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 40', '40');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 41', '41');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 42', '42');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 43', '43');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 44', '44');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 45', '45');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 46', '46');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 47', '47');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 48', '48');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 49', '49');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 50', '50');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 51', '51');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 52', '52');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 53', '53');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 54', '54');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 55', '55');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 56', '56');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 57', '57');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 58', '58');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 59', '59');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 60', '60');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 61', '61');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 62', '62');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 63', '63');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 64', '64');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 65', '65');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 66', '66');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 67', '67');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 68', '68');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 69', '69');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 70', '70');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 71', '71');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 72', '72');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 73', '73');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 74', '74');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 75', '75');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 76', '76');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 77', '77');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 78', '78');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 79', '79');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 80', '80');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 81', '81');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 82', '82');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 83', '83');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 84', '84');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 85', '85');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 86', '86');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 87', '87');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 88', '88');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 89', '89');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 90', '90');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 91', '91');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 92', '92');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 93', '93');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 94', '94');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 95', '95');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 96', '96');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 97', '97');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 98', '98');
INSERT INTO estado(nome, sigla) VALUES('Exemplo 99', '99');

INSERT INTO cidade(id, nome, estado_id) VALUES(1, 'Vargem Grande do Sul', 1);
INSERT INTO cidade(id, nome, estado_id) VALUES(2, 'São João da Boa Vista', 1);
INSERT INTO cidade(id, nome, estado_id) VALUES(3, 'Poços de Caldas', 2);
INSERT INTO cidade(id, nome, estado_id) VALUES(4, 'Curitiba', 3);

INSERT INTO cliente(id, nome, cidade_id) VALUES(1, 'Maria da Silva', 1);
INSERT INTO cliente(id, nome, cidade_id) VALUES(2, 'João da Silva', 2);
INSERT INTO cliente(id, nome, cidade_id) VALUES(3, 'José Fernandes', 3);
INSERT INTO cliente(id, nome, cidade_id) VALUES(4, 'Gilberto Oliveira', 4);

INSERT INTO produto(id, nome, preco, estoque) VALUES(1, 'Picanha', 100.00, 100.00);
INSERT INTO produto(id, nome, preco, estoque) VALUES(2, 'Cerveja', 6.99, 200.00);
INSERT INTO produto(id, nome, preco, estoque) VALUES(3, 'Mandioca', 4.50, 30.00);
INSERT INTO produto(id, nome, preco, estoque) VALUES(4, 'Cachaça', 3.89, 100.00);